thread_code: semaphore.h semaphore.cpp thread_code.cpp
	g++  --std=c++11 -lpthread semaphore.cpp thread_code.cpp
bank_simulation: semaphore.h semaphore.cpp bank_simulation.cpp
	g++ --std=c++11 -lpthread semaphore.cpp bank_simulation.cpp -o bank_simulation